# Generated by Django 6.0.3 on 2026-04-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Objects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="objectsdata",
            table="Objects",
        ),
    ]
