# Generated by Django 6.0.3 on 2026-04-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Camera", "0002_delete_objects"),
    ]

    operations = [
        migrations.AddField(
            model_name="persons",
            name="count",
            field=models.IntegerField(default=0),
        ),
    ]
