# Generated by Django 6.0.3 on 2026-04-16 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreateCamera",
            fields=[
                ("Cam_id", models.AutoField(primary_key=True, serialize=False)),
                ("Cam_name", models.CharField(max_length=100)),
                ("Cam_location", models.CharField(max_length=100)),
                ("ip_address", models.CharField(max_length=100)),
                ("rstp_url", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "Cameras",
            },
        ),
        migrations.CreateModel(
            name="Objects",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "ObjectsPhaser",
            },
        ),
        migrations.CreateModel(
            name="Persons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "Cam_ids",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Camera.createcamera",
                    ),
                ),
            ],
            options={
                "db_table": "Persons",
                "unique_together": {("Cam_ids", "date")},
            },
        ),
    ]
