# Generated by Django 6.0.3 on 2026-04-17 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Camera", "0003_persons_count"),
        ("UserData", "0002_alter_userd_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_unknown", models.BooleanField(default=False)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Camera.createcamera",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="UserData.userd",
                    ),
                ),
            ],
        ),
    ]
