# Generated by Django 5.2.13 on 2026-04-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camera', '0004_detectionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='previous',
            field=models.IntegerField(default=0),
        ),
    ]
