# Generated by Django 5.2.13 on 2026-04-18 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Camera', '0005_persons_previous'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetectionLog',
        ),
    ]
