# Generated by Django 5.2.13 on 2026-04-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserD',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='User/')),
                ('FaceEncoding', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
