# Generated by Django 6.0.3 on 2026-04-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreateCamera",
            fields=[
                ("Cam_id", models.AutoField(primary_key=True, serialize=False)),
                ("Cam_name", models.CharField(max_length=100)),
                ("Cam_location", models.CharField(max_length=100)),
                ("ip_address", models.CharField(max_length=100)),
                ("rstp_url", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "Cameras",
            },
        ),
    ]
