# Generated by Django 5.2.13 on 2026-04-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectsData',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
            ],
            options={
                'db_table': 'Objects',
            },
        ),
    ]
