# Generated by Django 6.0.3 on 2026-04-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ObjectsData",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.TextField()),
            ],
        ),
    ]
