# Generated by Django 6.0.3 on 2026-04-13 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UserData", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="userd",
            table="User",
        ),
    ]
