# Generated by Django 5.2.13 on 2026-04-18 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camera', '0006_delete_detectionlog'),
        ('ObjectDetectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectCount',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Count', models.IntegerField(default=0)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('CamRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_counts', to='Camera.createcamera')),
                ('ObjectRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='ObjectDetectors.objectdetector')),
            ],
            options={
                'db_table': 'ObjectCounts',
                'unique_together': {('ObjectRef', 'CamRef')},
            },
        ),
    ]
