# Generated by Django 5.2.13 on 2026-04-18 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camera', '0006_delete_detectionlog'),
        ('ObjectDetectors', '0002_objectcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='verify_data',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Verified', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
                ('CamRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verify_data', to='Camera.createcamera')),
                ('ObjectRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verify_data', to='ObjectDetectors.objectdetector')),
            ],
        ),
    ]
